In [8]:
#Importing pandas and numpy
import pandas as pd
import numpy as np


#Reads the concrete data and shows the first 5 features
concrete = pd.read_csv("concrete_data.csv")
concrete.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [9]:
#To understand features better
concrete.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [10]:
#Find if any null value exists ( which in this case there are no null values)
concrete.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [11]:
#Splitting the data as predictor and target
# Since we want to predict 'Strength' we choose it as the target and rest of them as the predictors
predictors = concrete[concrete.columns[concrete.columns != 'Strength']]
target = concrete['Strength']

#Normalization of predictors
predictors_n = (predictors - predictors.mean()) / predictors.std()

#Obtaining the number of columns in normalized predictors
n_cols = predictors_n.shape[1]

In [12]:
"""
Keras, 'Sequential' and 'Dense' functions were imported
Sequential is used to initialize and define the model,
then a hidden layer with 10 nodes that has 'relu' as activation function
were created, and with a 1 node output was added. Finally the model
was compiled with 'adam' optimizer and loss value of mean squared error.
The function return the created model"""

import keras
from keras.models import Sequential
from keras.layers import Dense

def reg_mod():
    model = Sequential()
    model.add(Dense(10,activation='relu',name="hidden",input_shape=(n_cols,)))
    model.add(Dense(1))

    model.compile(optimizer='adam',loss='mean_squared_error')
    return model

In [14]:
#Model was defined
model = reg_mod()

In [15]:
#importing the 'train_test_split' function
from sklearn.model_selection import train_test_split

#mean_squared_error function imported
from sklearn.metrics import mean_squared_error

""" to split the data into
trainin and test values, with the 'test_size = 0.3' parameter, our
#data will be split as %70 training and %30 test"""
msq = np.zeros(50)
for i in range(0,50):
    x_train, x_test, y_train, y_test = train_test_split(predictors_n,target,test_size=0.3,)

    #Model was trained with the splitted training predictors and target
    model.fit(x_train, y_train, epochs=100, verbose=0)

    #Predictions were made using the splitted test predictors
    predictions = model.predict(x_test)

    #Mean squared error was calculated comparing the newly predicted values with splitted test value
    msq[i] = mean_squared_error(y_test,predictions)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 791us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 795us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 731us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 730us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 785us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 730us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 791us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 791us/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step

In [16]:
#Mean of mean squared errors
msq_mean = np.mean(msq)

In [17]:
msq_mean

104.95934498128146

In [18]:
#Standart deviation of mean squared errors
msq_std = np.std(msq)

In [19]:
msq_std

11.320141098999645

msq_mean in Part A 
54.64671918698059

msq_std in Part A
21.247859362027345

msq_mean in Part B
48.06712347860784

msq_std in part B
43.91140511152317

We can easily see that increasing epoch while applying normalization increased our mean of msq, but that also caused the std to decrease. This also means that more epochs doesn't mean less error.